Traceback (most recent call last):
  File "./filter.contigs.py", line 405, in <module>
    main()
  File "./filter.contigs.py", line 310, in main
    first_record = next(SeqIO.parse(infile, 'fasta'))
  File "/Users/ahuynh/miniforge3/envs/7210_test/lib/python2.7/site-packages/Bio/SeqIO/FastaIO.py", line 178, in FastaIterator
    with as_handle(handle, "rU") as handle:
  File "/Users/ahuynh/miniforge3/envs/7210_test/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/ahuynh/miniforge3/envs/7210_test/lib/python2.7/site-packages/Bio/File.py", line 120, in as_handle
    with open(handleish, mode, **kwargs) as fp:
IOError: [Errno 2] No such file or directory: './asm/spades/contigs.fasta'
